Expand tabs to 4 spaces and trim trailing spaces

diff --git a/src/skel b/src/skel
--- a/src/skel
+++ b/src/skel
@@ -31,10 +31,10 @@ if [ -r /etc/default/cis-hardening ]; then
     . /etc/default/cis-hardening
 fi
 if [ -z "$CIS_ROOT_DIR" ]; then
-	 echo "There is no /etc/default/cis-hardening file nor cis-hardening directory in current environment." 
-	 echo "Cannot source CIS_ROOT_DIR variable, aborting."
-	exit 128
-fi 
+     echo "There is no /etc/default/cis-hardening file nor cis-hardening directory in current environment."
+     echo "Cannot source CIS_ROOT_DIR variable, aborting."
+    exit 128
+fi
 
 # Main function, will call the proper functions given the configuration (audit, enabled, disabled)
 [ -r "$CIS_ROOT_DIR"/lib/main.sh ] && . $CIS_ROOT_DIR/lib/main.sh
